[phases.setup]
nixPkgs = ["nodejs_20", "google-chrome-stable"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node backend/src/server.js"

[variables]
PORT = "8080"
NODE_ENV = "production"
